### ISSUE TITLE
config deleted when set before get

### ISSUE THREAD

**Issue by apolinux** [Luracast/Config#1]
I try to do this example

The config file is
return [
...
'mt' => [
        'size_list_mts' => 20 ,
        'max_sending_tries' => 3,
        'delay_loop_cli' => 1000000, // microseconds
        'start_sending_time' => 8 , // hours
        'end_sending_time' => 19 , // hours
    ],
...
];
the example that gets the error is
...
Config::set('config.mt.end_sending_time', $hour1+1);
echo "config mt after";print_r(Config::get('config.mt'));

In this example, the set is called before get and shows me:

,config mtArray
(
    [start_sending_time] => 12
    [end_sending_time] => 13
)

But when I get before set, in this example, the answer is correct:

echo "config mt before";print_r(Config::get('config.mt'));
        Config::set('config.mt.start_sending_time', (int)$hour1);
        Config::set('config.mt.end_sending_time', $hour1+1);
        echo "config mt after";print_r(Config::get('config.mt'));

.config mt beforeArray
(
    [size_list_mts] => 20
    [max_sending_tries] => 3
    [delay_loop_cli] => 1000000
    [start_sending_time] => 8
    [end_sending_time] => 19
)
config mt afterArray
(
    [size_list_mts] => 20
    [max_sending_tries] => 3
    [delay_loop_cli] => 1000000
    [start_sending_time] => 8
    [end_sending_time] => 19
)

Please fix this.

thanks!

**Comment by apolinux** [comment]
I just added a patch to fix this.
https://github.com/apolinux/Config/tree/patch-1

**Comment by Arul-** [comment]
Thanks a lot, @apolinux for bringing this up and proposing a fix. Now this issue is fixed and test is added to make sure
