### ISSUE TITLE
Exception on missing config option

### ISSUE THREAD

**Issue by gugglegum** [Luracast/Config#2]
In most cases I would prefer an exception would be thrown instead of handling possible `NULL` value on every `->get()` call. Is it possible? Is this package alive or abandoned already?

**Comment by Arul-** [comment]
The project is alive and in use. But this use case won't be supported!

**Comment by gugglegum** [comment]
Why don't you want to implement this feature? In most cases if some option is missing -- it's better (safier) to interrupt execution than continue with `NULL` value. Because in some cases processing with `NULL` value may be unexpectedly destructive. Or you prefer to add:
```
if ($host === null) {
    throw new Exception('Missing config option "database.host"');
}
```
after each `$config->get('database.host');` ?

**Comment by Arul-** [comment]
Will give it another thought and let you know!

**Comment by Arul-** [comment]
How about a `getOrThrow` method that throws an exception when the value is null?

**Comment by gugglegum** [comment]
> How about a `getOrThrow` method that throws an exception when the value is null?

Yes, it's acceptable. Good solution that doesn't break existing behavior.

**Comment by Arul-** [comment]
Latest version 2.0.2 has this feature now!

**Comment by gugglegum** [comment]
Thank you very much!
